name: Event-PVP-Plugin
version: 1.0.0
main: de.zfzfg.eventplugin.EventPlugin
api-version: 1.19
author: zfzfg
depend: [Vault]
softdepend: [Multiverse-Core]

commands:
  pvp:
    description: Unified PvP command with sub-commands
    usage: /<command> <challenge|accept|deny|spectate|leave|surrender|draw>
    aliases: [pvpwager]
    
  pvpa:
    description: Send a PvP wager request with full configuration
    usage: /<command> <player> <wager> <amount> <arena> <equipment>
    aliases: [pvprequest]
    
  pvpanswer:
    description: Respond to a PvP wager request
    usage: /<command> <wager> <amount> [arena] [equipment]
    aliases: [pvprespond]
    
  pvpyes:
    description: Accept the counter-offer
    usage: /<command>
    aliases: [pvpaccept, pvpconfirm]
    
  pvpno:
    description: Decline the request/counter-offer
    usage: /<command>
    aliases: [pvpdecline, pvpcancel]
    
  pvpadmin:
    description: Admin commands for PvPWager
    usage: /<command> [reload|stopall|info]
    permission: pvpwager.admin
    aliases: [pvpwageradmin]
    
  surrender:
    description: Surrender the current match
    usage: /<command>
    
  draw:
    description: Vote for a draw
    usage: /<command>
    
  pvpainfo:
    description: Show all available PvP commands and usage
    usage: /<command>
    aliases: [pvphelp, pvpinfo]

  event:
    description: Event Hauptbefehl
    usage: /<command> <join|leave|start|stop|forcestart|list>
    aliases: [ev, events]

  eventpvp:
    description: Unified Event+PvP Plugin command
    usage: /<command> reload
    aliases: [epvp, eventpvpreload]
    permission: eventpvp.admin

permissions:
  pvpwager.admin:
    description: Access to admin commands
    default: op
    
  pvpwager.bypass.betlimit:
    description: Bypass bet limits
    default: op
    
  pvpwager.use:
    description: Use PvP wager system
    default: true
    
  pvpwager.spectate:
    description: Spectate matches
    default: true
    
  pvpwager.command:
    description: Use command-based PvP requests
    default: true

  eventplugin.admin:
    description: Zugriff auf Event-Admin-Befehle
    default: op
  eventpvp.admin:
    description: Zugriff auf Event+PvP Unified Admin-Befehle
    default: op
  eventplugin.join:
    description: Erlaubt die Teilnahme an Events
    default: true
  eventpvp.opbypass:
    description: OP-Bypass für Command-Restriktionen
    default: op